### ISSUE TITLE
Typescript compatibility

### ISSUE THREAD

**Issue by kuncung38** [dimdenGD/ultimate-express#10]
Is it type-safe? Because i dont see @types/ultimate-express in npm site

**Comment by dimdenGD** [comment]
If you'll make a PR with .d.ts file I'll happily merge it. I don't have experience with TS stuff.

**Comment by dimdenGD** [comment]
Though your workaround probably wouldn't work since we don't include Express as module

**Comment by dimdenGD** [comment]
I haven't seen a way of publishing package to @types. Looks like its managed automatically from .d.ts in npm modules so that would including express as dependency, which I really wouldn't want to do. Looks like we have to make our own d.ts file afterall

**Comment by dalisoft** [comment]
@dimdenGD What if install `@types/express` as `dependency`, then use that as `typings` ?

**Comment by dalisoft** [comment]
> ```ts
> declare module 'ultimate-express' {
>   import express from 'express';
>   export = express;
> }
> ```

```diff
declare module 'ultimate-express' {
-  import express from 'express';
+  import express from '@types/express';
  export = express;
}
```

Like @hillac solution but alternative way

**Comment by kuncung38** [comment]
> > ```ts
> > declare module 'ultimate-express' {
> >   import express from 'express';
> >   export = express;
> > }
> > ```
> 
> ```diff
> declare module 'ultimate-express' {
> -  import express from 'express';
> +  import express from '@types/express';
>   export = express;
> }
> ```
> 
> Like @hillac solution but alternative way

Wow, is this possible? Feels like a simple solution

**Comment by dimdenGD** [comment]
I dont know how TS works, but wouldn't it notice that instances of objects are different from original ones?

**Comment by leosuncin** [comment]
Since this project its API is compatible with `express` I override `express` with `ultimate-express` in the **package.json**

```json
{
  "dependencies": {
    "express": "npm:ultimate-express@latest"
  },
  "devDependencies": {
    "@types/express": "latest",
    "typescript": "latest"
  }
}
```

Change _latest_ with the version of your choice

**Comment by cesco69** [comment]
Simple solution

`src/typings/ultimate-express.d.ts`
```ts
declare module 'ultimate-express' {
    import express from '@types/express';
    export = express;
}
```

`tsconfig.json`
```json
{
    ...
    "typeRoots": [
        "src/typings",
    ],
    ...
}
```

**Comment by cesco69** [comment]
It works!

Just a problem. Default export of express ia a function with no arguments:

```ts
express(): Express;
```
But `ultimate-express` accept an `settings` parameter (https://github.com/dimdenGD/ultimate-express/blob/main/src/application.js#L50C17-L50C26)

On typescript if try to add settings I show this error:

![image](https://github.com/user-attachments/assets/a3202c82-6322-4d07-afda-5bcf52af4f3f)

the workaround is mutate typescript error

![image](https://github.com/user-attachments/assets/d5398937-aaac-4b88-9d90-5a7c4d78b9cf)

**Comment by dimdenGD** [comment]
If you know how TS declaration file works, you can make PR to fix this: https://github.com/dimdenGD/ultimate-express/blob/main/src/types.d.ts
Unfortunately I don't have knowledge in it

**Comment by dimdenGD** [comment]
Should be all working in 1.3.1!

**Comment by kuncung38** [comment]
> Should be all working in 1.3.1!

Nice one!! So.. what is the solution? We can just use npm i uiltimate-express?? Does it already come with type safety feature?

**Comment by dimdenGD** [comment]
Yes

**Comment by nigrosimone** [comment]
This happen because "cookie-parser" get a different version of "express" types. Try to override express

```json
{
    "name": "test",
    "version": "1.0.0",
    "devDependencies": {
        "@types/cookie-parser": "^1.4.8",
        "typescript": "^5.6.3"
    },
    "scripts": {
        "build": "tsc"
    },
    "dependencies": {
        "cookie-parser": "^1.4.7",
        "ultimate-express": "^1.3.16",
        "express": "npm:ultimate-express" // <--------- override express with ultimate-express
    },
    "false": {}
}
```
