### ISSUE TITLE
Append headers not working

### ISSUE THREAD

**Issue by hillac** [dimdenGD/ultimate-express#13]
When I append multiple headers of the same type with res.append in ue they don't seem to be set in the browser. I discovered this because appending multiple set-cookie headers was failing to set cookies. I noticed that in chrome dev tools, the response for express has two different headers of the same name, while the response from ue is just a single comma separated header.

reproduction:
```javascript
import uexpress from 'ultimate-express';
import express from 'express';

const makeapp = async (iexpress, port) => {
  const app = iexpress();

  // allow fetch from browser
  app.use((req, res, next) => {
    res.append('Access-Control-Allow-Origin', '*');
    res.append('Access-Control-Allow-Methods', 'POST');
    res.append('Access-Control-Allow-Headers', 'Content-Type');
    res.append('Access-Control-Allow-Credentials', 'true');
    // if options return 200
    // if (req.method === 'OPTIONS') {
    //   res.status(200).end();
    //   return;
    // }
    next();
  });

  app.post('/test', (req, res) => {
    res.append('set-cookie', 'cookie1');
    res.append('set-cookie', 'cookie2');
    res.append('hi', 'hi1');
    res.append('hi', 'hi2');
    res.send('Hello');
  });

  app.listen(port, () => {
    console.log(`Server is running on http://localhost:${port}`);
  });

  //   const ops = { method: 'POST', headers: { 'Content-Type': 'application/json' } };
  //   const response = await fetch(`http://localhost:${port}/test`, ops);
  //   console.log(response.headers);
};

console.log('uexpress');
await makeapp(uexpress, 3000);
console.log('express');
await makeapp(express, 3001);
```
There's an additional bug where the above code fails if you fetch from browser console for ue if you dont uncomment the if statement that sends 200 for options.

I commented out the fetch and log because you can't see the difference using the node inbuilt fetch. If you use chrome dev tools you'll see it. Send the following in console to 3000 and 3001 then looks at the response in the network tab
```javascript
await fetch(`http://localhost:3000/test`, { method: 'POST', headers: { 'Content-Type': 'application/json' } });
```

Or an easier option is to do:
```bash
curl -i -X POST http://localhost:3000/test
```

You'll see ue sets 1 comma separated header while express sets 2.

It might be worth making a sort of fuzzing test that randomly (but reproducible with a seed) calls all the response augmentation methods with random inputs and confirms that `curl -i` looks the same for both, and similar for all the methods to read the req. Or at least copying over all the tests from express.js that test at an api level.

[Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) says that setting multiple cookies requires multiple set-cookie headers so I guess that's why express does it this way.

**Comment by dimdenGD** [comment]
Fixed
