### ISSUE TITLE
Handle errors in async handlers

### ISSUE THREAD

**Issue by hillac** [dimdenGD/ultimate-express#14]
Any chance you could support handling errors in async handlers? I use [express-async-errors](https://www.npmjs.com/package/express-async-errors) with express to avoid the ugly try catch next block in every handler. It would obviously have to be in an option since it's not normal express behavior.

**Comment by dwbboy** [comment]
router.js
第487行
`
out.catch(err => {
     throw err;
});`
改为
`
                            out.catch(err => {
                                this._handleError(err, req, res);
                                return resolve(true);
                            });`

**Comment by dimdenGD** [comment]
There's now an option to support async errors: `app.set('catch async errors', true)` in 1.3.0
