### ISSUE TITLE
Question about compression

### ISSUE THREAD

**Issue by cesco69** [dimdenGD/ultimate-express#19]
Hi, I'm migrating my project to "ultimate-expres". Everything works perfectly! Really great work. The only feature don't works anymore is the compression of json sent in the responses. Is there anything I can do to have this too?

**Comment by dimdenGD** [comment]
As mentioned in documentation, `compression` is not supported. It patches into methods that ultimate-express doesn't call or doesn't call in correct order. I made a reasonable attempt to support it but couldn't really figure it out, if you'll make a PR to fix the incompatibility, I'll happily merge it.
![image](https://github.com/user-attachments/assets/296f5844-4372-4c26-9fba-e254a811bd61)
