### ISSUE TITLE
Question: middleware and routing

### ISSUE THREAD

**Issue by cesco69** [dimdenGD/ultimate-express#33]
Hi @dimdenGD, I'm debugging `ultimate-express` and I have see that each middleware require a long round trip into `_routeRequest` of `router.js`, I want try to optimeze it, eg.:

```js
app.use(responseTime());
app.use(express.json({ limit: "100mb" }));
app.use(compression({ threshold: 1 }));
```

these middleware require to be applied into every route path, there isn't a way for make a short round trip into `_routeRequest` and make it faster?

**Comment by dimdenGD** [comment]
idk it looks as short as possible already to me
