### ISSUE TITLE
Question: optimize middleware, bodyParser just for POST method?

### ISSUE THREAD

**Issue by cesco69** [dimdenGD/ultimate-express#39]
@dimdenGD Thanks for `ultimate-express` and sorry for bad english! I have just one question, I want  optimize my routing resolution avoidind useless miggleware like the body parser middleware, in my case only `POST` method need it.

Instead of:
```js
express.use(express.json({ limit: '100kb', strict: false }));
```

I have made
```js
express.post('*', express.json({ limit: '100kb', strict: false }), (_req, _res, next) => next())
```

In this way
- `GET` method routing resolution are faster because are not affected by body parser callback?
- `POST` method routing resolution is same as `express.use(express.json({ limit: '100kb', strict: false }));`?

Thanks for your time!

PS. Maybe can be a performance-tips https://github.com/dimdenGD/ultimate-express?tab=readme-ov-file#performance-tips

**Comment by dimdenGD** [comment]
I think that should be faster, but probably by barely any amount, since it skips reading body for requests without it anyway.

**Comment by cesco69** [comment]
Ok, thanks!

**Comment by dimdenGD** [comment]
Also (_req, _res, next) => next() is useless

**Comment by cesco69** [comment]
Oh right! thanks!
