### ISSUE TITLE
Express api difference for req.params

### ISSUE THREAD

**Issue by hillac** [dimdenGD/ultimate-express#5]
Hey, I wanted to try this with my app but for a regex route with /*, ultimate express has a req.params different to express. Here's a simple reproduction:

```bash
npm i express ultimate-express
```
```javascript
const express = require('express');
// const express = require('ultimate-express');

const app = express();
app.get('/test/*', (req, res) => {
    console.log(req.params);
    res.send('Hello');
})
const port = 3000;
app.listen(port, () => {
    console.log(`Server is running on port ${port}`);
});
```

Then load localhost:3000/test/hello

The req.params is {} for ultimate express and { '0': 'hello' } for express.

**Comment by dimdenGD** [comment]
Thanks, fixed in 1.1.9.
