### ISSUE TITLE
Meaning of “declarative” in benchmark table

### ISSUE THREAD

**Issue by doxlik** [dimdenGD/ultimate-express#74]
Hello dear author of this magnificent framework. I have a question, in the table with benchmark result there are two tows related ultimate express, one is **ultimate-express** another one is **ultimate-express (declarative)** and the one marked **declarative** is much faster. So can you please explain what is the difference of them?

**Comment by dimdenGD** [comment]
It's for routes that don't have any dynamic behavior and can be compiled into declarative response. For example
```js
app.get("/test", (req, res) => {
    res.header("X-Test", "Test");
    res.send("Hi");
});
```

**Comment by doxlik** [comment]
Sorry, by “ routes that don't have any dynamic behavior” you mean routes that does not have path variables?

**Comment by dimdenGD** [comment]
Function of route itself also matters

**Comment by doxlik** [comment]
Very interesting. And how do you determine the behaviour of the handler (function of route)? You take its string representation and check if it only set data to response or have some dynamic logic like going to db? It is extremely interesting and I will be very grateful if you share your experience.

**Comment by dimdenGD** [comment]
See https://github.com/dimdenGD/ultimate-express/blob/main/src/declarative.js, it parses JS to determine if only allowed functions/variables are used
