### ISSUE TITLE
Assigning value to const

### ISSUE THREAD

**Issue by ismoiliy98** [dimdenGD/ultimate-express#75]
https://github.com/dimdenGD/ultimate-express/blob/8c1e6796d42151130503663714b6a15c8947603a/src/utils.js#L111
https://github.com/dimdenGD/ultimate-express/blob/8c1e6796d42151130503663714b6a15c8947603a/src/utils.js#L122
https://github.com/dimdenGD/ultimate-express/blob/8c1e6796d42151130503663714b6a15c8947603a/src/utils.js#L135

Assigning value to const?

**Comment by nigrosimone** [comment]
Side note. This code Is from https://github.com/dimdenGD/ultimate-express/pull/54 and from https://github.com/expressjs/express/pull/6066

**Comment by cesco69** [comment]
`acceptParams()` is unused:
https://github.com/search?q=repo%3AdimdenGD%2Fultimate-express%20acceptParams&type=code
