### ISSUE TITLE
Type declaration import error

### ISSUE THREAD

**Issue by zeta-squared** [dimdenGD/ultimate-express#76]
I am not sure if this is a typo or intentional but
```import "@types/express"```
raises the following error during compilation
```TS6173: Cannot import type declaration files. Consider importing 'express' instead of '@types/express'.```
As expected changing the import statement fixes it. My `tsconfig` is below for reference.
```
{
  "exclude": ["**/models/*.ts"],
  "include": ["./src", "./config"],
  "compilerOptions": {
    "baseUrl": "./src",
    "module": "nodenext",
    "moduleResolution": "nodenext",
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noEmitOnError": true,
    "target": "es2017",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "resolveJsonModule": true,
    "typeRoots": ["./node_modules/@types", "./src/types"]
  }
}
```

**Comment by nigrosimone** [comment]
Try to add `skipLibCheck` with `true`

> TypeScript will type check the code you specifically refer to in your app’s source code.

https://www.typescriptlang.org/tsconfig/#skipLibCheck

**Comment by zeta-squared** [comment]
Thanks for that.

**Comment by zeta-squared** [comment]
Thanks for that.
